#!/bin/bash
dlog(){
	echo "$@" >> vdot.log
}
showlog(){
	test ! -f vdot.log && return 0
	gedit vdot.log > /dev/null 2>/dev/null &
	return 0
}
dlog "ARGS: $@" >vdot.log
test -z "$1" && exit 0
test ! -f "$1" && dlog "no found: $1" && showlog && exit 1
test ! -s "$1" && dlog "empty file: $1" && showlog && exit 0
dot -Txlib $@ >> vdot.log 2>&1
exitcode=$?
dlog "EXITCODE=$exitcode"
vcnt=`cat vdot.log 2>/dev/null | wc -l` 
if [ $vcnt -gt 2 ]
then
	showlog
else
	dot -Tsvg $1 > $1.svg 2>>vdot.log
fi
exit $exitcode
